# Generated by Django 2.2.17 on 2021-03-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0003_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'action-adventure'), (2, 'comedy'), (3, 'crime'), (4, 'horror'), (5, 'sci-fi')], default=1),
            preserve_default=False,
        ),
    ]
