# Generated by Django 2.2.17 on 2021-04-01 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0004_film_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'action-adventure'), (2, 'comedy'), (3, 'crime'), (4, 'horror'), (5, 'sci-fi')]),
        ),
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='film_site.Category'),
        ),
    ]
