# Generated by Django 2.2.17 on 2021-04-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0005_auto_20210401_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'action-adventure'), (2, 'comedy'), (3, 'crime'), (4, 'horror'), (5, 'sci-fi')], default=1),
            preserve_default=False,
        ),
    ]
