# Generated by Django 2.2.17 on 2021-04-02 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Action-Adventure'), (2, 'Comedy'), (3, 'Crime'), (4, 'Horror'), (5, 'Sci-fi')]),
        ),
        migrations.AlterField(
            model_name='film',
            name='img',
            field=models.ImageField(blank=True, upload_to='film_images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
