# Generated by Django 2.2.17 on 2021-04-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0008_auto_20210402_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='views',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Action-Adventure'), (2, 'Comedy'), (3, 'Crime'), (4, 'Horror'), (5, 'Sci-fi')], default=1),
            preserve_default=False,
        ),
    ]
