# Generated by Django 2.2.17 on 2021-04-03 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0010_auto_20210402_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 15, 35, 44, 48311, tzinfo=utc), null=True),
        ),
    ]
