# Generated by Django 2.2.17 on 2021-04-03 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0013_auto_20210403_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 15, 46, 57, 807869, tzinfo=utc), editable=False),
        ),
    ]
