# Generated by Django 2.2.17 on 2021-04-03 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0016_auto_20210403_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 16, 4, 17, 696473, tzinfo=utc), editable=False),
        ),
    ]
