# Generated by Django 2.2.17 on 2021-04-03 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0020_auto_20210403_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 16, 36, 31, 773366, tzinfo=utc), editable=False),
        ),
    ]
