# Generated by Django 2.2.17 on 2021-04-04 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0024_auto_20210403_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 13, 39, 41, 403999, tzinfo=utc), editable=False),
        ),
    ]
