# Generated by Django 2.2.17 on 2021-04-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0027_auto_20210404_2002'),
        ('film_site', '0029_auto_20210404_2144'),
    ]

    operations = [
    ]
