# Generated by Django 2.2.17 on 2021-04-05 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0030_merge_20210405_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 12, 57, 34, 69787, tzinfo=utc), editable=False),
        ),
    ]
