# Generated by Django 2.2.17 on 2021-04-05 13:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0031_auto_20210405_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 13, 24, 42, 248739, tzinfo=utc), editable=False),
        ),
    ]
